import 'dart:typed_data';

import 'package:cross_file/cross_file.dart';
import 'package:file_picker/file_picker.dart';
import 'package:flutter/material.dart';
import 'package:flutter_riverpod/flutter_riverpod.dart';
import 'package:olcerim/core/database/daos/student_dao.dart';
import 'package:olcerim/core/services/excel_service.dart';
import 'package:olcerim/features/students/presentation/controllers/student_providers.dart';

class StudentImportView extends ConsumerStatefulWidget { const StudentImportView({this.classroomId, super.key}); final int? classroomId; @override ConsumerState<StudentImportView> createState() => _StudentImportViewState(); }
class _StudentImportViewState extends ConsumerState<StudentImportView> {
  final service = ExcelService(); StudentFilePreview? preview; StudentPreviewValidation? validation; int? nameColumn; int? numberColumn; String? fileName; bool busy = false;
  @override Widget build(BuildContext context) { if (widget.classroomId == null) return const Scaffold(body: Center(child: Text('Öğrenci içe aktarmak için önce bir sınıf açın.'))); return Scaffold(appBar: AppBar(title: const Text('Öğrenci içe aktar')), body: Align(alignment: Alignment.topCenter, child: SingleChildScrollView(padding: const EdgeInsets.all(24), child: ConstrainedBox(constraints: const BoxConstraints(maxWidth: 760), child: Column(crossAxisAlignment: CrossAxisAlignment.stretch, children: [Text('Excel veya CSV sınıf listenizi seçin', style: Theme.of(context).textTheme.headlineMedium), const SizedBox(height: 8), const Text('Dosya yalnız cihazınızda okunur. İçe aktarmadan önce kolonları ve hatalı satırları kontrol edebilirsiniz.'), const SizedBox(height: 24), FilledButton.tonalIcon(onPressed: busy ? null : _pickFile, icon: const Icon(Icons.file_open), label: Text(fileName ?? 'Dosya seç')), if (busy) const Padding(padding: EdgeInsets.only(top: 16), child: LinearProgressIndicator()), if (preview case final data?) ...[const SizedBox(height: 24), _columnSelector(data), const SizedBox(height: 16), _previewTable(data), if (validation case final result?) ...[const SizedBox(height: 16), if (result.errors.isNotEmpty) Card(child: Padding(padding: const EdgeInsets.all(16), child: Column(crossAxisAlignment: CrossAxisAlignment.start, children: [Text('${result.errors.length} satırda sorun bulundu', style: Theme.of(context).textTheme.titleMedium), const SizedBox(height: 8), ...result.errors.take(8).map(Text.new)]))), const SizedBox(height: 16), FilledButton(onPressed: result.isValid && !busy ? _import : null, child: Text('${result.validRows.length} öğrenciyi içe aktar'))]]])))))); }
  Widget _columnSelector(StudentFilePreview data) { final items = List.generate(data.headers.length, (index) => DropdownMenuItem<int>(value: index, child: Text(data.headers[index].isEmpty ? 'Kolon ${index + 1}' : data.headers[index]))); return Wrap(runSpacing: 12, spacing: 12, children: [SizedBox(width: 320, child: DropdownButtonFormField<int>(initialValue: nameColumn, decoration: const InputDecoration(labelText: 'Ad soyad kolonu'), items: items, onChanged: (value) => setState(() { nameColumn = value; _validate(); }))), SizedBox(width: 320, child: DropdownButtonFormField<int>(initialValue: numberColumn, decoration: const InputDecoration(labelText: 'Okul no kolonu (opsiyonel)'), items: [const DropdownMenuItem<int>(value: null, child: Text('Yok')), ...items], onChanged: (value) => setState(() { numberColumn = value; _validate(); })))]); }
  Widget _previewTable(StudentFilePreview data) { final columns = data.headers.map((header) => DataColumn(label: Text(header.isEmpty ? 'Kolon' : header))).toList(); final rows = data.rows.take(8).map((row) => DataRow(cells: List.generate(columns.length, (index) => DataCell(Text(index < row.length ? row[index] : ''))))).toList(); return SingleChildScrollView(scrollDirection: Axis.horizontal, child: DataTable(columns: columns, rows: rows)); }
  Future<void> _pickFile() async { final result = await FilePicker.platform.pickFiles(type: FileType.custom, allowedExtensions: const ['xlsx', 'csv'], withData: true); if (result == null) return; final file = result.files.single; Uint8List? bytes = file.bytes; if (bytes == null && file.path != null) bytes = await XFile(file.path!).readAsBytes(); if (bytes == null) return; setState(() { busy = true; fileName = file.name; }); try { final parsed = await service.parseStudentList(bytes, file.extension ?? ''); if (!mounted) return; setState(() { preview = parsed; nameColumn = parsed.suggestedNameColumn; numberColumn = parsed.suggestedNumberColumn; busy = false; _validate(); }); } catch (error) { if (mounted) setState(() => busy = false); if (mounted) ScaffoldMessenger.of(context).showSnackBar(const SnackBar(content: Text('Dosya okunamadı. Dosya biçimini kontrol edip tekrar deneyin.'))); } }
  void _validate() { final data = preview; final name = nameColumn; if (data == null || name == null) { validation = null; return; } validation = service.validate(data, nameColumn: name, numberColumn: numberColumn); }
  Future<void> _import() async { final result = validation; if (result == null || !result.isValid) return; setState(() => busy = true); try { await ref.read(studentRepositoryProvider).importStudents(widget.classroomId!, result.validRows.map((row) => StudentImportRecord(fullName: row.fullName, schoolNumber: row.schoolNumber)).toList()); if (!mounted) return; ScaffoldMessenger.of(context).showSnackBar(SnackBar(content: Text('${result.validRows.length} öğrenci içe aktarıldı.'))); Navigator.pop(context); } catch (_) { if (mounted) ScaffoldMessenger.of(context).showSnackBar(const SnackBar(content: Text('Öğrenciler içe aktarılamadı. Aynı okul numarasını kullanan öğrencileri kontrol edin.'))); } finally { if (mounted) setState(() => busy = false); } }
}
